AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - db/schema.rb
    - 'db/migrate/**/*'
    - 'lib/tasks/**/*'
    - '**/bin/*'
    - '**/config/**/*'
    - '**/vendor/**/*'
      
# Disabled cops:
Bundler/OrderedGems:
  Enabled: false
Layout/LeadingCommentSpace:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/ExpandPathArguments:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
# Maybe add these back later?
Metrics/MethodLength:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
