AllCops:
  Exclude:
    - db/schema.rb
    - '**/bin/*'
    - '**/config/**/*'
    - '**/vendor/**/*'
      
# Disabled cops:
Bundler/OrderedGems:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
# Maybe add these back later?
Metrics/MethodLength:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
